### ISSUE TITLE
TVHeadend URL 404 Not Found

### ISSUE THREAD

**Issue by jake404** [fHDHR/fHDHR_plugin_interface_hdhr#16]
I have fHDHR setup with the TVHeadend plugin and the HDHR Interface plugin. When I go to the HDHR section in the webui and click on the TVHeadend URL I get 404 Not Found (http://192.168.29.102:5004/hdhr/tvheadend).

**Comment by jake404** [comment]
I only have HDHR in Plex and I'm getting this in the log file:

> Apr 01, 2021 17:27:16.397 [0x7fd7a4ea6700] DEBUG - DVR:Device: Device was alive, refreshed device://tv.plex.grabbers.hdhomerun/80a7c76.
Apr 01, 2021 17:27:16.397 [0x7fd7a4ea6700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/888ccadd at http://192.168.29.102:5004/hdhr/tvheadend
Apr 01, 2021 17:27:16.397 [0x7fd7a4ea6700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/888ccadd was already known, refreshing database info
Apr 01, 2021 17:27:16.397 [0x7fd7a4ea6700] DEBUG - HTTP requesting GET http://192.168.29.102:5004/hdhr/tvheadend/discover.json
Apr 01, 2021 17:27:16.402 [0x7fd7a4ea6700] DEBUG - HTTP 200 response from GET http://192.168.29.102:5004/hdhr/tvheadend/discover.json
Apr 01, 2021 17:27:16.402 [0x7fd7a4ea6700] DEBUG - HTTP requesting GET http://192.168.29.102:5004/hdhr/tvheadend/lineup_status.json
Apr 01, 2021 17:27:16.406 [0x7fd7a4ea6700] DEBUG - HTTP 200 response from GET http://192.168.29.102:5004/hdhr/tvheadend/lineup_status.json
Apr 01, 2021 17:27:16.409 [0x7fd7a4ea6700] DEBUG - DVR:Device: Device was alive, refreshed device://tv.plex.grabbers.hdhomerun/80a7c76.
Apr 01, 2021 17:27:16.409 [0x7fd7a4ea6700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/80a7c76 died
Apr 01, 2021 17:27:16.410 [0x7fd7a4ea6700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/80a7c76 died

**Comment by deathbybandaid** [comment]
any logs for fHDHR?

**Comment by deathbybandaid** [comment]
what other plugins do you have for fHDHR?

**Comment by jake404** [comment]
I only have the TVHeadend plugin and the HDHR Interface plugin.

Here is a log from fHDHR with DEBUG level: https://pastebin.com/jxX8Bt2G

**Comment by deathbybandaid** [comment]
Not seeing anything goofy in either log.

Remove 'dvr' from plex, restart plexmediaserver, reload webpage, and readd to plex.

**Comment by jake404** [comment]
I have recreated DVR in Plex and so far it doesn't show the error. But usually, it only lasts a few days.
